#!/usr/bin/php
<?php

echo "##  Verificando erros PHP... ##\n";

$output = array();
$return = 0;
exec('git rev-parse --verify HEAD 2> /dev/null', $output, $return);
$against = $return == 0 ? 'HEAD' : '4b825dc642cb6eb9a060e54bf8d69288fbee4904';

exec("git diff-index --cached --name-only {$against}", $output);

$filename_pattern_PHP = '/\.php$/';

$exit_status = 0;
$error = 0;
foreach ($output as $file) {
    
    if (file_exists($file) && preg_match($filename_pattern_PHP, $file)) {
        $lint_output = array();

        exec("php -l " . escapeshellarg($file), $lint_poutput, $return);
        if ($return != 0) {
            echo implode("\n", $lint_output), "\n";
            $exit_status = 1;
        }
    }
}

echo '##   Executando testes   ##';
exec('phpunit.phar .', $output);
if(!preg_match('@OK \(\d+ tests, \d+ assertions\)@', $output[count($output)-1])){
    echo implode("\n", $output);
    $exit_status = 0;
}else $exit_status = 1;

exit($exit_status);